FROM node:24-alpine

WORKDIR /app

COPY package.json .
COPY package-lock.json .
RUN npm install


# Copy the rest of the application code to the working directory
COPY . .

RUN npm install -g nodemon
# Expose the port your Node.js application listens on

CMD ["npm", "run", "dev"]

