version: "3.7"
services:
  db:
    image: postgres:17
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: recicleaqui
    volumes:
      - ./db:/db

  app:
    build:
      dockerfile: ./Dockerfile-dev
    ports:
      - 3000:3000
      - 8000:8000
      - 8080:8080
    volumes:
      - ./:/app
    env_file: ./.env.development.local